# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.2'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/asoneji/test-pods-repo.git'

target 'sample-ios-project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-ios-project
  pod 'Analytics', '3.9.0'
  pod 'TestMeLib', '0.1.0'

  target 'sample-ios-projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample-ios-projectUITests' do
    # Pods for testing
  end

end
